version: '2'
services:
  sa_api_gateway:
    #build: .
    image: diegoagr97/sa_api_gateway
    command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 4000 -b '0.0.0.0'"
    ports:
      - "4001:4001"
